#include "comms_api.h"
#include "wifi_http_client.h"

void comms_init(const char* ssid, const char* password) 
{
    wifi_network_init(ssid, password);
}

void comms_start_polling(void) 
{
    start_live_data_monitor();
}



// main/comms/comms_api.c

// #include "comms_api.h"
// // #include "esp_http_client.h"
// #include "esp_log.h"
// #include "cJSON.h"
// #include "freertos/FreeRTOS.h"
// #include "freertos/task.h"
// #include "../backend/data_model.h"
// #include <string.h>

// static const char *TAG = "COMMS_POST";

// // The background task that handles the HTTP request
// static void http_post_pump_control_task(void *pvParameters) 
// {
//     // 1. SAFELY EXTRACT ALL REQUIRED DATA FROM BACKEND
//     int display_id = 0;
//     char du_serial[32] = "";
//     int nozzle_id = 0;
//     DispenseMode tx_mode = MODE_NONE;
//     float tx_value = 0.0f;
//     PaymentMethod tx_pay_method = PAYMENT_NONE;

//     if (lock_station_model()) {
//         DisplayNode* disp = get_active_display();
//         DispenserNode* du = get_active_dispenser();
//         NozzleNode* noz = get_active_transaction_nozzle();

//         if (disp) display_id = disp->display_id;
//         if (du) strncpy(du_serial, du->serial_number, sizeof(du_serial) - 1);
//         if (noz) nozzle_id = noz->nozzle_id;
        
//         tx_mode = get_transaction_mode();
//         tx_value = get_transaction_value();
//         tx_pay_method = get_payment_method();

//         unlock_station_model();
//     }

//     // 2. MAP INTERNAL ENUMS TO SERVER-EXPECTED STRINGS
//     const char* preset_type_str = (tx_mode == MODE_VOLUME) ? "PRESET_VOLUME" : "PRESET_AMOUNT";
    
//     const char* payment_mode_str = "CASH"; // Fallback default
//     if (tx_pay_method == PAYMENT_QR) payment_mode_str = "UPI";
//     else if (tx_pay_method == PAYMENT_CARD) payment_mode_str = "CARD";

//     char preset_val_str[16];
//     snprintf(preset_val_str, sizeof(preset_val_str), "%.2f", tx_value);

//     char noz_id_str[16];
//     snprintf(noz_id_str, sizeof(noz_id_str), "%d", nozzle_id);

//     // 3. BUILD THE EXACT cJSON STRUCTURE
//     cJSON *root = cJSON_CreateObject();
//     cJSON *pump_control = cJSON_CreateObject();
//     cJSON *select_preset = cJSON_CreateObject();

//     // Populate SELECT_PRESET
//     cJSON_AddStringToObject(select_preset, "PRESET_TYPE", preset_type_str);
//     cJSON_AddStringToObject(select_preset, "PRESET_VALUE", preset_val_str);
//     cJSON_AddStringToObject(select_preset, "PAYMENT_MODE", payment_mode_str);
//     cJSON_AddStringToObject(select_preset, "INVOICE_ID", "");
//     cJSON_AddStringToObject(select_preset, "OVERRIDE", "DISABLE");

//     // Populate PUMP_CONTROL
//     cJSON_AddNumberToObject(pump_control, "DISPLAY_POS_ID", display_id);
//     cJSON_AddStringToObject(pump_control, "DISPENSER_SERIAL_NUMBER", du_serial);
//     cJSON_AddStringToObject(pump_control, "NOZZLE_POS_ID", noz_id_str);
//     cJSON_AddNumberToObject(pump_control, "DISPLAY_SERIAL_NUMBER", 12000000); // Or fetch dynamically if available
    
//     // Assemble hierarchy
//     cJSON_AddItemToObject(pump_control, "SELECT_PRESET", select_preset);
//     cJSON_AddItemToObject(root, "PUMP_CONTROL", pump_control);

//     // Render JSON to a string
//     char *post_data = cJSON_PrintUnformatted(root);
//     cJSON_Delete(root); // Free the JSON object memory immediately

//     ESP_LOGI(TAG, "Executing POST to server with payload: %s", post_data);

//     // 4. CONFIGURE AND EXECUTE HTTP POST
//     esp_http_client_config_t config = {
//         .url = "http://192.168.4.1/PUMP_CONTROL",
//         .method = HTTP_METHOD_POST,
//         .timeout_ms = 5000, // 5 second timeout so it doesn't hang forever
//     };
//     esp_http_client_handle_t client = esp_http_client_init(&config);

//     esp_http_client_set_header(client, "Content-Type", "application/json");
//     esp_http_client_set_post_field(client, post_data, strlen(post_data));

//     esp_err_t err = esp_http_client_perform(client);
//     if (err == ESP_OK) {
//         ESP_LOGI(TAG, "HTTP POST Status = %d, content_length = %lld",
//                  esp_http_client_get_status_code(client),
//                  esp_http_client_get_content_length(client));
//     } else {
//         ESP_LOGE(TAG, "HTTP POST request failed: %s", esp_err_to_name(err));
//     }

//     // 5. CLEANUP & DELETE TASK
//     esp_http_client_cleanup(client);
//     free(post_data); // Free the string generated by cJSON_PrintUnformatted
    
//     // Terminate this specific FreeRTOS task since its job is done
//     vTaskDelete(NULL); 
// }

// // The exposed function that spawns the background task
// void comms_send_pump_control(void) 
// {
//     // Spawn task: name "post_task", stack 4096 bytes, priority 5
//     xTaskCreate(http_post_pump_control_task, "post_task", 4096, NULL, 5, NULL);
// }